version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0
  github-cli: circleci/github-cli@2.2.0

workflows:
  generate-audits:
    jobs:
      - hugo/build: # Let's factorize this duplication later
          name: build-staging-frago
          version: 0.120.3
          hugo-extra-flags: --config hugo.toml --baseURL https://audits.test.iroco.co/
          html-proofer: false
          persist-to-workspace: false # We manage workspace ourselve below since we don't want to use the job's defaults
          pre-steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
          post-steps:
            - run : tar czf audits.test.iroco.co.tar.gz public # Hugo generates site into ./public
            - persist_to_workspace:
                root: .
                paths:
                  - audits.test.iroco.co.tar.gz
            - store_artifacts:
                path: audits.test.iroco.co.tar.gz
                destination: audits.test.iroco.co.tar.gz
          filters:
              tags:
                  only: /.*/
      - hugo/build:
          name: build-prod-frago
          version: 0.120.3
          hugo-extra-flags: --config hugo.toml --baseURL https://audits.iroco.co/
          html-proofer: false
          persist-to-workspace: false # We manage workspace ourselve below since we don't want to use the job's defaults
          pre-steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
          post-steps:
            - run : tar czf audits.iroco.co.tar.gz public # Hugo generates site into ./public
            - persist_to_workspace:
                root: .
                paths:
                  - audits.iroco.co.tar.gz
            - store_artifacts:
                path: audits.iroco.co.tar.gz
                destination: audits.iroco.co.tar.gz
          filters:
              tags:
                  only: /.*/
      - github-cli/release:
          version: 2.39.1
          name: github-cli-release
          tag: ${CIRCLE_TAG}
          title: "Release ${CIRCLE_TAG} by circleci"
          prerelease: false
          draft: false
          notes-file: ''
          requires:
            - "build-staging-frago"
            - "build-prod-frago"
          pre-steps:
            - attach_workspace:
                at: /tmp/artifacts
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\..*/
