version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0

workflows:
  generate-audits:
    jobs:
      - hugo/build:
          version: 0.120.3
          hugo-extra-flags: --config hugo.toml
          html-proofer: false
          pre-steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
          post-steps:
            - store_artifacts:
                path: public
                destination: audits
