version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0

workflows:
  generate-audits:
    jobs:
      - hugo/build: # Hugo generates site into ./public
          version: 0.120.3
          hugo-extra-flags: --config hugo.toml --baseURL https://audits.test.iroco.co/
          html-proofer: false
          pre-steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
          post-steps:
            - run : tar czf audits.test.iroco.co.tar.gz public
                  # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
            - persist_to_workspace:
                # Must be an absolute path, or relative path from working_directory. This is a directory in the execution
                # environment which is taken to be the root directory of the workspace.
                root: .
                # Must be relative path from root
                paths:
                  - audits.test.iroco.co.tar.gz
            - store_artifacts:
                path: audits.test.iroco.co.tar.gz
                destination: audits.test.iroco.co.tar.gz
      - hugo/build: # Hugo generates site into ./public
          version: 0.120.3
          hugo-extra-flags: --config hugo.toml --baseURL https://audits.iroco.co/
          html-proofer: false
          pre-steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
          post-steps:
            - run : tar czf audits.iroco.co.tar.gz public
            - persist_to_workspace:
                # Must be an absolute path, or relative path from working_directory. This is a directory in the execution
                # environment which is taken to be the root directory of the workspace.
                root: .
                # Must be relative path from root
                paths:
                  - audits.iroco.co.tar.gz
            - store_artifacts:
                path: audits.iroco.co.tar.gz
                destination: audits.iroco.co.tar.gz