version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0

workflows:
  generate-audits:
    jobs:
      - hugo/build:
          pre-steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
