version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0
  github-cli: circleci/github-cli@2.2.0

jobs:
  gh-release:
    docker:
      - image: cimg/base:stable
    steps:
      - github-cli/setup
      - github-cli/clone
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          command: |
            gh release create --title "Release ${CIRCLE_TAG} from circleCI" --notes "" "${CIRCLE_TAG}"
            gh release upload  "${CIRCLE_TAG}" "/tmp/artifacts/audits.test.iroco.co.tar.gz" "/tmp/artifacts/audits.iroco.co.tar.gz"
            # gh release upload  "${CIRCLE_TAG}" "/tmp/artifacts/audits.test.iroco.co.tar.gz# https;//audits.test.iroco.co" "/tmp/artifacts/audits.iroco.co.tar.gz# https://audits.test.iroco.co"
workflows:
  generate-audits:
    jobs:
      - hugo/build: # Let's factorize this duplication later
          name: build-staging-frago
          version: 0.120.3
          hugo-extra-flags: --config hugo.toml --baseURL https://audits.test.iroco.co/
          html-proofer: false
          persist-to-workspace: false # We manage workspace ourselve below since we don't want to use the job's defaults
          pre-steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
          post-steps:
            - run : tar czf audits.test.iroco.co.tar.gz public # Hugo generates site into ./public
            - persist_to_workspace:
                root: .
                paths:
                  - audits.test.iroco.co.tar.gz
            - store_artifacts:
                path: audits.test.iroco.co.tar.gz
                destination: audits.test.iroco.co.tar.gz
          filters:
              tags:
                  only: /.*/
      - hugo/build:
          name: build-prod-frago
          version: 0.120.3
          hugo-extra-flags: --config hugo.toml --baseURL https://audits.iroco.co/
          html-proofer: false
          persist-to-workspace: false # We manage workspace ourselve below since we don't want to use the job's defaults
          pre-steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
          post-steps:
            - run : tar czf audits.iroco.co.tar.gz public # Hugo generates site into ./public
            - persist_to_workspace:
                root: .
                paths:
                  - audits.iroco.co.tar.gz
            - store_artifacts:
                path: audits.iroco.co.tar.gz
                destination: audits.iroco.co.tar.gz
          filters:
              tags:
                  only: /.*/
      - gh-release:
          requires:
            - "build-staging-frago"
            - "build-prod-frago"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\..*/
